# Generated by Django 3.1.7 on 2021-03-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aatienda', '0002_auto_20210316_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuto',
            name='descripccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
