# Generated by Django 3.1.7 on 2021-03-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aatienda', '0003_prodcuto_descripccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuto',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
