# Generated by Django 3.1.7 on 2021-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aatienda', '0004_prodcuto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuto',
            name='codigo_modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
