# Generated by Django 3.1.7 on 2021-03-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulos'),
        ),
    ]
