# Generated by Django 3.1.7 on 2021-04-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_por_enviar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('num_exterior', models.CharField(max_length=200)),
                ('num_interior', models.CharField(max_length=200)),
                ('referencias', models.CharField(max_length=1000)),
                ('envio', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('productos', models.CharField(max_length=1000)),
                ('cantidad', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
