# Generated by Django 3.1.7 on 2021-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_por_enviar',
            name='sesion',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
